### ISSUE TITLE
Repeated error 500 on reader

### ISSUE THREAD

**Issue by Retartist** [pagermon/pagermon#501]
I'm using the [7c745e8](https://github.com/pagermon/pagermon/commit/7c745e873c1c0306254aac3a2a0bfeb8de433bab) version of pagermon I believe. 

Pagermon is on a raspien OS, running on a RPI with pm2 managing both reader.sh and the server.

On my reader.sh i'm repeatedly getting variations of

```
2|reader  | 2022-02-15 03:09:07: 0002408: 
2|reader  | Message failed to deliver. StatusCodeError: 500 - "{\"message\":\"Error - address or message missing\"}"
2|reader  | Retrying in 1000 ms
```

with some normal messages in between but I believe I'm missing most of the pager messages on the system I am monitoring.

in addition i'm getting this error on my node-app.stderr.log files 

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:526:11)
    at ServerResponse.header (/home/pi/pagermon/server/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/pi/pagermon/server/node_modules/express/lib/response.js:170:12)
    at done (/home/pi/pagermon/server/node_modules/express/lib/response.js:1004:10)
    at tryHandleCache (/home/pi/pagermon/server/node_modules/ejs/lib/ejs.js:257:5)
    at View.exports.renderFile [as engine] (/home/pi/pagermon/server/node_modules/ejs/lib/ejs.js:480:10)
    at View.render (/home/pi/pagermon/server/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/pi/pagermon/server/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/pi/pagermon/server/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/pi/pagermon/server/node_modules/express/lib/response.js:1008:7)
    at /home/pi/pagermon/server/app.js:196:7
    at Layer.handle_error (/home/pi/pagermon/server/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/pi/pagermon/server/node_modules/express/lib/router/index.js:315:13)
    at /home/pi/pagermon/server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/pagermon/server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/pagermon/server/node_modules/express/lib/router/index.js:275:10)
```

Is this an error with the program or an issue with signal reception and subsequent decoding of messages? I do suspect that I am having signal issues but I'm unable to check too easily since the device is set up in a friends house and I am using VNC to remote into it.

**Comment by marshyonline** [comment]
The 500 the client is receiving is because there is no body to the message - its empty
The client respond differently to this kind of error so it doesn't end up in the loop - ill need to add some logic to the sever and client for this. 
I would likely say its a signal issue given the body of the message is empty by a capcode is received or they are sending empty messages
