### ISSUE TITLE
Cannot enable plugins on aliases

### ISSUE THREAD

**Issue by RIKIKU** [pagermon/pagermon#522]
**Describe the bug**
Plugins cannot be enabled from the edit alias page.

**To Reproduce**

1. Ensure a plugin enabled and configured from the settings page. 
2. Ensure you are in a new session and have not tried to create a new alias first.
3. Edit an existing Alias
4. Scroll down to Plugins and attempt to click `Enable sending messages that match this alias via <plugin name>`
5. The tick box will not tick and an error is produced in the browser debug console

**Expected behavior**
The tickbox should tick and the options should appear for that plugin.

**Screenshots**
![image](https://user-images.githubusercontent.com/10013348/174195807-4f2efe56-deaf-4a05-987a-eba7a5c290cb.png)

**Environment information:**
 - OS:  Official Docker image running on Ubuntu x86 (same issue in non official image)
 - DB: Maria DB running in Docker.
 - Accessed via  Nginx reverse proxy over HTTPS with custom host name.
 - Other details: Confirmed to occur in Firefox and Chromium based browsers

**Additional context**
Works as expected if you first try to add an alias and tick the box. You don't have to save that alias, just use the feature. After that if you try to edit an existing alias it will work as expected for a while. refreshing the browser appears to allow the error to return. 

Error from the browser console:
````
TypeError: Cannot create property 'Pushover' on string '"\"\\\"{\\\\\\\"Discord\\\\\\\":{},\\\\\\\"Filter\\\\\\\":{},\\\\\\\"Gotify\\\\\\\":{},\\\\\\\"MessageRepeat\\\\\\\":{},\\\\\\\"MicrosoftTeams\\\\\\\":{},\\\\\\\"Pushover\\\\\\\":{},\\\\\\\"RegexReplace\\\\\\\":{},\\\\\\\"SMTP\\\\\\\":{},\\\\\\\"Shell\\\\\\\":{},\\\\\\\"Slack\\\\\\\":{},\\\\\\\"Telegram\\\\\\\":{},\\\\\\\"Template\\\\\\\":{},\\\\\\\"Twitter\\\\\\\":{}}\\\"\""'
    at fn.assign (eval at compile (angular.js:15358:15), <anonymous>:4:1047)
    at Object.$$writeModelToScope (angular.js:28810:5)
    at angular.js:28804:9
    at g (angular.js:28723:9)
    at e (angular.js:28706:9)
    at Object.$$runValidators (angular.js:28650:5)
    at Object.$$parseAndValidate (angular.js:28791:5)
    at Object.$commitViewValue (angular.js:28757:5)
    at angular.js:28898:9
    at b.$eval (angular.js:18161:16)
````

**Comment by RIKIKU** [comment]
This is likely a result of dirty data. Deleting the alias and creating it again fixes the issue. Not worth fixing this.
